/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
 */
package io.apimatic.examples;
public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://examples.apimatic.io/apps/calculator";

}
